package com.demo.entity;
// Generated 2018-6-6 9:41:50 by Hibernate Tools 5.2.8.Final

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {

	private Integer id;
	private String name;

	public Author() {
	}

	public Author(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
