package com.demo.entity;
// Generated 2018-6-6 9:41:50 by Hibernate Tools 5.2.8.Final

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer price;
	private Integer authorid;

	public Book() {
	}

	public Book(String name, Integer price, Integer authorid) {
		this.name = name;
		this.price = price;
		this.authorid = authorid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getAuthorid() {
		return this.authorid;
	}

	public void setAuthorid(Integer authorid) {
		this.authorid = authorid;
	}

}
